version: "3.9"
services:
  postgres:
    image: postgres
    container_name: scandium-db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - scandium-data:/data/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: ScandiumDB
  scandium-api:
    build: .
    ports:
      - "3007:80"
    depends_on:
      - postgres
    command: ["dotnet", "ef", "database update"]

volumes:
  scandium-data: